theme: jekyll-theme-slate
title: Repository Handbook Project
description: We are using Cornell's Repository Handbook to update our instutitutional repository policies and processes at the Unviersity of Pittsburgh. We also intend to allow the forking of this repository for use by other universities for similar projects.
baseurl: /repository-handbook/
